name: sotfbee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias principales
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  http: ^1.4.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  flutter_animate: ^4.2.0
  dio: ^5.4.2
  get_it: ^7.6.4
  image_picker: ^0.8.7+3
  app_links: ^3.5.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.1
  dartz: ^0.10.1
  uuid: ^4.0.0
  flutter_tts: ^3.8.5
  speech_to_text: ^7.1.0
  
  fuzzywuzzy: ^0.2.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  
  audioplayers: ^5.2.1
  wakelock_plus: ^1.1.0
  flutter_displaymode: ^0.6.0
  connectivity_plus: ^5.0.2
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  
  # Base de datos
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^1.0.0  # Versión corregida
  path: ^1.8.0
  
  # Almacenamiento alternativo
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/loader.json
    - assets/images/Logo.png